### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-patrozada#1]
Super buen trabajo @patrozada 

Algunas pistas para acabarlo:

- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Mueve el `li` fuera del componente Card, de esta manera Card es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] No asumas que todos los pokemons tienen 2 tipos, eso es trampa!
- [x] Apaña estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:
- Mover el array de pokemons a otro archivo e importarlo en App.
- Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
- Añadir un click a Card que: marca o desmarca el pokemon como favorito en el array del estado de App.
- Pasar este dato a Card por props
- Pintar la tarjeta con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by patrozada** [comment]
Hola @nasivuela!
He conseguido añadir favoritos y que cambien sus estilos desde el estado en app, pero, aunque funciona, no he conseguido que actualice el estado como yo quiero, que es que lo deje todo como está y sólo cambie el isFav del currentTarget. 
Lo he intentado también con prevState, pero tampoco consigo que sólo se cambie ese valor.
Si me da tiempo lo inetnto de nuevo.

**Comment by nasivuela** [comment]
Excelente trabajo @patrozada !!!

El problema con el que te encuentras se puede apañar con un .map. Recuerda que la clave `pokemon` del estado contiene un array. Cuando hagas un setState, tienes que devolver un objeto con esta clave y su nuevo valor (un array con los mismo items, pero uno de ellos modificados ;)

Cierro!

![](https://media.giphy.com/media/13GIgrGdslD9oQ/giphy.gif)
